apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: container-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: container-demo
  template:
    metadata:
      labels:
        app: container-demo
    spec:
      containers:
      - name: container-demo
        image: container-demo:latest
        # For Minikube local development.
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: container-demo
spec:
  selector:
    app: container-demo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30443
  type: NodePort